// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'caret': string;
  'caretOpen': string;
  'checkboxIcon': string;
  'checkboxInput': string;
  'columnName': string;
  'enable': string;
  'footer': string;
  'grabHandle': string;
  'grip': string;
  'help': string;
  'item': string;
  'list': string;
  'menu': string;
  'name': string;
  'perkName': string;
  'rank': string;
  'sortsOnly': string;
  'splitButton': string;
  'toggle': string;
}
export const cssExports: CssExports;
export = cssExports;
