// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'columnHeader': string;
  'columns': string;
  'count': string;
  'divider': string;
  'header': string;
  'modeHelp': string;
  'perk': string;
  'perkFinder': string;
  'perkName': string;
  'result': string;
  'resultIcon': string;
  'resultMessage': string;
  'resultNote': string;
  'resultText': string;
  'section': string;
  'sectionHelp': string;
  'sections': string;
  'selected': string;
  'title': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export = cssExports;
