// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chip': string;
  'chipActive': string;
  'menu': string;
  'menuButton': string;
  'section': string;
  'sectionBody': string;
  'sectionTitle': string;
}
export const cssExports: CssExports;
export = cssExports;
