// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categoryChevron': string;
  'categoryLabel': string;
  'categoryRow': string;
  'categoryRowOpen': string;
  'flyout': string;
  'flyoutBody': string;
  'flyoutEmpty': string;
  'flyoutHeader': string;
  'flyoutSearch': string;
  'menu': string;
  'menuButton': string;
  'optionRow': string;
  'optionRowActive': string;
}
export const cssExports: CssExports;
export = cssExports;
