// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ariaLive': string;
  'armoryItemIcon': string;
  'deleteIcon': string;
  'filterBarButton': string;
  'filterHelp': string;
  'ghostCycleCount': string;
  'ghostKeyHelp': string;
  'ghostLayer': string;
  'ghostSuffix': string;
  'highlightedItem': string;
  'inputWrap': string;
  'invalid': string;
  'keyHelp': string;
  'menu': string;
  'menuItem': string;
  'menuItemIcon': string;
  'menuItemQuery': string;
  'namedQueryBody': string;
  'open': string;
  'openButton': string;
  'openInArmoryLabel': string;
  'saveSearchButton': string;
  'searchBar': string;
  'textHighlight': string;
}
export const cssExports: CssExports;
export = cssExports;
